### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by tejasmanohar** [tejasmanohar/npm-algos#9]
Write a contribution guide `CONTRIBUTING.md`

**Comment by qw3rtman** [comment]
Should probably include instructions on publishing a package to npm in this too.

**Comment by jalcine** [comment]
Shouldn't the publishing permission be only held by the maintainer and core contributors? Unless I'm misunderstanding your statement.

**Comment by qw3rtman** [comment]
@jalcine, I was referring to publishing on npm (node package manager), not this Github repo. Anyone can publish to a package on npm, just as always.

**Comment by tejasmanohar** [comment]
@qw3rtman Yeah, I'll probably link instructions for those who want to implement things that are not well implemented in modules and are relevant here.

**Comment by tejasmanohar** [comment]
https://github.com/tejasmanohar/npm-algos/pull/15
